/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hardware.dispenser;

public class DispenserClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DispenserClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DispenserClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DispenserClass obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DispenserControlJNI.delete_DispenserClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSerialPort(int value) {
    DispenserControlJNI.DispenserClass_SerialPort_set(swigCPtr, this, value);
  }

  public int getSerialPort() {
    return DispenserControlJNI.DispenserClass_SerialPort_get(swigCPtr, this);
  }

  public void setSuccessConnect(boolean value) {
    DispenserControlJNI.DispenserClass_SuccessConnect_set(swigCPtr, this, value);
  }

  public boolean getSuccessConnect() {
    return DispenserControlJNI.DispenserClass_SuccessConnect_get(swigCPtr, this);
  }

  public void setInitialized(boolean value) {
    DispenserControlJNI.DispenserClass_Initialized_set(swigCPtr, this, value);
  }

  public boolean getInitialized() {
    return DispenserControlJNI.DispenserClass_Initialized_get(swigCPtr, this);
  }

  public void setPortO(int value) {
    DispenserControlJNI.DispenserClass_PortO_set(swigCPtr, this, value);
  }

  public int getPortO() {
    return DispenserControlJNI.DispenserClass_PortO_get(swigCPtr, this);
  }

  public void setCardsInDispenser(boolean value) {
    DispenserControlJNI.DispenserClass_CardsInDispenser_set(swigCPtr, this, value);
  }

  public boolean getCardsInDispenser() {
    return DispenserControlJNI.DispenserClass_CardsInDispenser_get(swigCPtr, this);
  }

  public void setCardInGate(boolean value) {
    DispenserControlJNI.DispenserClass_CardInGate_set(swigCPtr, this, value);
  }

  public boolean getCardInGate() {
    return DispenserControlJNI.DispenserClass_CardInGate_get(swigCPtr, this);
  }

  public void setRFICCardInGate(boolean value) {
    DispenserControlJNI.DispenserClass_RFICCardInGate_set(swigCPtr, this, value);
  }

  public boolean getRFICCardInGate() {
    return DispenserControlJNI.DispenserClass_RFICCardInGate_get(swigCPtr, this);
  }

  public void setDispenserFull(boolean value) {
    DispenserControlJNI.DispenserClass_DispenserFull_set(swigCPtr, this, value);
  }

  public boolean getDispenserFull() {
    return DispenserControlJNI.DispenserClass_DispenserFull_get(swigCPtr, this);
  }

  public void setRecyclingBoxFull(boolean value) {
    DispenserControlJNI.DispenserClass_RecyclingBoxFull_set(swigCPtr, this, value);
  }

  public boolean getRecyclingBoxFull() {
    return DispenserControlJNI.DispenserClass_RecyclingBoxFull_get(swigCPtr, this);
  }

  public void setErrorOCode(String value) {
    DispenserControlJNI.DispenserClass_ErrorOCode_set(swigCPtr, this, value);
  }

  public String getErrorOCode() {
    return DispenserControlJNI.DispenserClass_ErrorOCode_get(swigCPtr, this);
  }

  public void setErrorOMsg(String value) {
    DispenserControlJNI.DispenserClass_ErrorOMsg_set(swigCPtr, this, value);
  }

  public String getErrorOMsg() {
    return DispenserControlJNI.DispenserClass_ErrorOMsg_get(swigCPtr, this);
  }

  public void setLoggerLevel(int value) {
    DispenserControlJNI.DispenserClass_LoggerLevel_set(swigCPtr, this, value);
  }

  public int getLoggerLevel() {
    return DispenserControlJNI.DispenserClass_LoggerLevel_get(swigCPtr, this);
  }

  public void setLogFilePath(String value) {
    DispenserControlJNI.DispenserClass_LogFilePath_set(swigCPtr, this, value);
  }

  public String getLogFilePath() {
    return DispenserControlJNI.DispenserClass_LogFilePath_get(swigCPtr, this);
  }

  public void setMaxPorts(int value) {
    DispenserControlJNI.DispenserClass_MaxPorts_set(swigCPtr, this, value);
  }

  public int getMaxPorts() {
    return DispenserControlJNI.DispenserClass_MaxPorts_get(swigCPtr, this);
  }

  public void setMaxInitAttempts(int value) {
    DispenserControlJNI.DispenserClass_MaxInitAttempts_set(swigCPtr, this, value);
  }

  public int getMaxInitAttempts() {
    return DispenserControlJNI.DispenserClass_MaxInitAttempts_get(swigCPtr, this);
  }

  public void setShortTime(int value) {
    DispenserControlJNI.DispenserClass_ShortTime_set(swigCPtr, this, value);
  }

  public int getShortTime() {
    return DispenserControlJNI.DispenserClass_ShortTime_get(swigCPtr, this);
  }

  public void setLongTime(int value) {
    DispenserControlJNI.DispenserClass_LongTime_set(swigCPtr, this, value);
  }

  public int getLongTime() {
    return DispenserControlJNI.DispenserClass_LongTime_get(swigCPtr, this);
  }

  public DispenserClass() {
    this(DispenserControlJNI.new_DispenserClass(), true);
  }

  public SpdlogLevels_t SearchSpdlogLevel(int Code) {
    return new SpdlogLevels_t(DispenserControlJNI.DispenserClass_SearchSpdlogLevel(swigCPtr, this, Code), true);
  }

  public void SetSpdlogLevel() {
    DispenserControlJNI.DispenserClass_SetSpdlogLevel(swigCPtr, this);
  }

  public StatusCodesRow_t SearchSuccessCode0(String SCode) {
    return new StatusCodesRow_t(DispenserControlJNI.DispenserClass_SearchSuccessCode0(swigCPtr, this, SCode), true);
  }

  public StatusCodesRow_t SearchSuccessCode1(String SCode) {
    return new StatusCodesRow_t(DispenserControlJNI.DispenserClass_SearchSuccessCode1(swigCPtr, this, SCode), true);
  }

  public StatusCodesRow_t SearchSuccessCode2(String SCode) {
    return new StatusCodesRow_t(DispenserControlJNI.DispenserClass_SearchSuccessCode2(swigCPtr, this, SCode), true);
  }

  public ErrorCodesRow_t SearchErrorCode(String ErrorC) {
    return new ErrorCodesRow_t(DispenserControlJNI.DispenserClass_SearchErrorCode(swigCPtr, this, ErrorC), true);
  }

  public ErrorCodeExComm_t SearchErrorCodeExComm(int Code) {
    return new ErrorCodeExComm_t(DispenserControlJNI.DispenserClass_SearchErrorCodeExComm(swigCPtr, this, Code), true);
  }

  public int StIdle() {
    return DispenserControlJNI.DispenserClass_StIdle(swigCPtr, this);
  }

  public int StConnect() {
    return DispenserControlJNI.DispenserClass_StConnect(swigCPtr, this);
  }

  public int StInit() {
    return DispenserControlJNI.DispenserClass_StInit(swigCPtr, this);
  }

  public int StWait() {
    return DispenserControlJNI.DispenserClass_StWait(swigCPtr, this);
  }

  public int StMovingMotor() {
    return DispenserControlJNI.DispenserClass_StMovingMotor(swigCPtr, this);
  }

  public int StHandingCard() {
    return DispenserControlJNI.DispenserClass_StHandingCard(swigCPtr, this);
  }

  public int StError() {
    return DispenserControlJNI.DispenserClass_StError(swigCPtr, this);
  }

  public void InitLogger(String Path) {
    DispenserControlJNI.DispenserClass_InitLogger(swigCPtr, this, Path);
  }

  public int ConnectSerial(int Port) {
    return DispenserControlJNI.DispenserClass_ConnectSerial(swigCPtr, this, Port);
  }

  public int ScanPorts() {
    return DispenserControlJNI.DispenserClass_ScanPorts(swigCPtr, this);
  }

  public int SendingCommand(SWIGTYPE_p_std__vectorT_unsigned_char_t Comm, int AdTime) {
    return DispenserControlJNI.DispenserClass_SendingCommand(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Comm), AdTime);
  }

  public int ExecuteCommand(SWIGTYPE_p_std__vectorT_unsigned_char_t Comm, int AdTime) {
    return DispenserControlJNI.DispenserClass_ExecuteCommand(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Comm), AdTime);
  }

  public int HandleResponse(SWIGTYPE_p_std__vectorT_unsigned_char_t Response, int Cm, int Pm) {
    return DispenserControlJNI.DispenserClass_HandleResponse(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Response), Cm, Pm);
  }

  public int WriteAck() {
    return DispenserControlJNI.DispenserClass_WriteAck(swigCPtr, this);
  }

  public int HandleResponseSuccess(SWIGTYPE_p_std__vectorT_unsigned_char_t Response) {
    return DispenserControlJNI.DispenserClass_HandleResponseSuccess(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Response));
  }

  public int HandleResponseError(SWIGTYPE_p_std__vectorT_unsigned_char_t Response) {
    return DispenserControlJNI.DispenserClass_HandleResponseError(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_char_t.getCPtr(Response));
  }

  public int InitDispenser() {
    return DispenserControlJNI.DispenserClass_InitDispenser(swigCPtr, this);
  }

  public int DispenseCard() {
    return DispenserControlJNI.DispenserClass_DispenseCard(swigCPtr, this);
  }

  public int CheckStatus() {
    return DispenserControlJNI.DispenserClass_CheckStatus(swigCPtr, this);
  }

  public int ReturnCardToBox() {
    return DispenserControlJNI.DispenserClass_ReturnCardToBox(swigCPtr, this);
  }

  public void PrintCheck() {
    DispenserControlJNI.DispenserClass_PrintCheck(swigCPtr, this);
  }

}
