/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040101
#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } } while (0)


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


#include <string>


#include "Dispenser.hpp"
#include "StateMachine.hpp"
#include "DispenserControl.hpp"
using namespace DispenserControl;
using namespace StateMachine;
using namespace Dispenser;


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_StatusCodesRow_1t_1Status_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Dispenser::StatusCodesRow_t *arg1 = (Dispenser::StatusCodesRow_t *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::StatusCodesRow_t **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->Status = *arg2;
}


SWIGEXPORT jstring JNICALL Java_hardware_dispenser_DispenserControlJNI_StatusCodesRow_1t_1Status_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Dispenser::StatusCodesRow_t *arg1 = (Dispenser::StatusCodesRow_t *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::StatusCodesRow_t **)&jarg1; 
  result = (std::string *) & ((arg1)->Status);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_StatusCodesRow_1t_1Message_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Dispenser::StatusCodesRow_t *arg1 = (Dispenser::StatusCodesRow_t *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::StatusCodesRow_t **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->Message = *arg2;
}


SWIGEXPORT jstring JNICALL Java_hardware_dispenser_DispenserControlJNI_StatusCodesRow_1t_1Message_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Dispenser::StatusCodesRow_t *arg1 = (Dispenser::StatusCodesRow_t *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::StatusCodesRow_t **)&jarg1; 
  result = (std::string *) & ((arg1)->Message);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_StatusCodesRow_1t_1Priority_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Dispenser::StatusCodesRow_t *arg1 = (Dispenser::StatusCodesRow_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::StatusCodesRow_t **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->Priority = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_StatusCodesRow_1t_1Priority_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::StatusCodesRow_t *arg1 = (Dispenser::StatusCodesRow_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::StatusCodesRow_t **)&jarg1; 
  result = (int) ((arg1)->Priority);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_new_1StatusCodesRow_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Dispenser::StatusCodesRow_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Dispenser::StatusCodesRow_t *)new Dispenser::StatusCodesRow_t();
  *(Dispenser::StatusCodesRow_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_delete_1StatusCodesRow_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Dispenser::StatusCodesRow_t *arg1 = (Dispenser::StatusCodesRow_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Dispenser::StatusCodesRow_t **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_ErrorCodesRow_1t_1ErrorCode_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Dispenser::ErrorCodesRow_t *arg1 = (Dispenser::ErrorCodesRow_t *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::ErrorCodesRow_t **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->ErrorCode = *arg2;
}


SWIGEXPORT jstring JNICALL Java_hardware_dispenser_DispenserControlJNI_ErrorCodesRow_1t_1ErrorCode_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Dispenser::ErrorCodesRow_t *arg1 = (Dispenser::ErrorCodesRow_t *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::ErrorCodesRow_t **)&jarg1; 
  result = (std::string *) & ((arg1)->ErrorCode);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_ErrorCodesRow_1t_1Message_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Dispenser::ErrorCodesRow_t *arg1 = (Dispenser::ErrorCodesRow_t *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::ErrorCodesRow_t **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->Message = *arg2;
}


SWIGEXPORT jstring JNICALL Java_hardware_dispenser_DispenserControlJNI_ErrorCodesRow_1t_1Message_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Dispenser::ErrorCodesRow_t *arg1 = (Dispenser::ErrorCodesRow_t *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::ErrorCodesRow_t **)&jarg1; 
  result = (std::string *) & ((arg1)->Message);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_ErrorCodesRow_1t_1Priority_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Dispenser::ErrorCodesRow_t *arg1 = (Dispenser::ErrorCodesRow_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::ErrorCodesRow_t **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->Priority = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_ErrorCodesRow_1t_1Priority_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::ErrorCodesRow_t *arg1 = (Dispenser::ErrorCodesRow_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::ErrorCodesRow_t **)&jarg1; 
  result = (int) ((arg1)->Priority);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_new_1ErrorCodesRow_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Dispenser::ErrorCodesRow_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Dispenser::ErrorCodesRow_t *)new Dispenser::ErrorCodesRow_t();
  *(Dispenser::ErrorCodesRow_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_delete_1ErrorCodesRow_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Dispenser::ErrorCodesRow_t *arg1 = (Dispenser::ErrorCodesRow_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Dispenser::ErrorCodesRow_t **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_ErrorCodeExComm_1t_1Code_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Dispenser::ErrorCodeExComm_t *arg1 = (Dispenser::ErrorCodeExComm_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::ErrorCodeExComm_t **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->Code = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_ErrorCodeExComm_1t_1Code_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::ErrorCodeExComm_t *arg1 = (Dispenser::ErrorCodeExComm_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::ErrorCodeExComm_t **)&jarg1; 
  result = (int) ((arg1)->Code);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_ErrorCodeExComm_1t_1Message_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Dispenser::ErrorCodeExComm_t *arg1 = (Dispenser::ErrorCodeExComm_t *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::ErrorCodeExComm_t **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->Message = *arg2;
}


SWIGEXPORT jstring JNICALL Java_hardware_dispenser_DispenserControlJNI_ErrorCodeExComm_1t_1Message_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Dispenser::ErrorCodeExComm_t *arg1 = (Dispenser::ErrorCodeExComm_t *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::ErrorCodeExComm_t **)&jarg1; 
  result = (std::string *) & ((arg1)->Message);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_ErrorCodeExComm_1t_1Priority_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Dispenser::ErrorCodeExComm_t *arg1 = (Dispenser::ErrorCodeExComm_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::ErrorCodeExComm_t **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->Priority = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_ErrorCodeExComm_1t_1Priority_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::ErrorCodeExComm_t *arg1 = (Dispenser::ErrorCodeExComm_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::ErrorCodeExComm_t **)&jarg1; 
  result = (int) ((arg1)->Priority);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_new_1ErrorCodeExComm_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Dispenser::ErrorCodeExComm_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Dispenser::ErrorCodeExComm_t *)new Dispenser::ErrorCodeExComm_t();
  *(Dispenser::ErrorCodeExComm_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_delete_1ErrorCodeExComm_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Dispenser::ErrorCodeExComm_t *arg1 = (Dispenser::ErrorCodeExComm_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Dispenser::ErrorCodeExComm_t **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_SpdlogLevels_1t_1Code_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Dispenser::SpdlogLevels_t *arg1 = (Dispenser::SpdlogLevels_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::SpdlogLevels_t **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->Code = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_SpdlogLevels_1t_1Code_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::SpdlogLevels_t *arg1 = (Dispenser::SpdlogLevels_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::SpdlogLevels_t **)&jarg1; 
  result = (int) ((arg1)->Code);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_SpdlogLevels_1t_1Message_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Dispenser::SpdlogLevels_t *arg1 = (Dispenser::SpdlogLevels_t *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::SpdlogLevels_t **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->Message = *arg2;
}


SWIGEXPORT jstring JNICALL Java_hardware_dispenser_DispenserControlJNI_SpdlogLevels_1t_1Message_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Dispenser::SpdlogLevels_t *arg1 = (Dispenser::SpdlogLevels_t *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::SpdlogLevels_t **)&jarg1; 
  result = (std::string *) & ((arg1)->Message);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_new_1SpdlogLevels_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Dispenser::SpdlogLevels_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Dispenser::SpdlogLevels_t *)new Dispenser::SpdlogLevels_t();
  *(Dispenser::SpdlogLevels_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_delete_1SpdlogLevels_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Dispenser::SpdlogLevels_t *arg1 = (Dispenser::SpdlogLevels_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Dispenser::SpdlogLevels_t **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1SerialPort_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->SerialPort = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1SerialPort_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int) ((arg1)->SerialPort);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1SuccessConnect_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->SuccessConnect = arg2;
}


SWIGEXPORT jboolean JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1SuccessConnect_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (bool) ((arg1)->SuccessConnect);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1Initialized_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->Initialized = arg2;
}


SWIGEXPORT jboolean JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1Initialized_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (bool) ((arg1)->Initialized);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1PortO_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->PortO = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1PortO_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int) ((arg1)->PortO);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1CardsInDispenser_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->CardsInDispenser = arg2;
}


SWIGEXPORT jboolean JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1CardsInDispenser_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (bool) ((arg1)->CardsInDispenser);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1CardInGate_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->CardInGate = arg2;
}


SWIGEXPORT jboolean JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1CardInGate_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (bool) ((arg1)->CardInGate);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1RFICCardInGate_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->RFICCardInGate = arg2;
}


SWIGEXPORT jboolean JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1RFICCardInGate_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (bool) ((arg1)->RFICCardInGate);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1DispenserFull_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->DispenserFull = arg2;
}


SWIGEXPORT jboolean JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1DispenserFull_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (bool) ((arg1)->DispenserFull);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1RecyclingBoxFull_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->RecyclingBoxFull = arg2;
}


SWIGEXPORT jboolean JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1RecyclingBoxFull_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (bool) ((arg1)->RecyclingBoxFull);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1ErrorOCode_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->ErrorOCode = *arg2;
}


SWIGEXPORT jstring JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1ErrorOCode_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (std::string *) & ((arg1)->ErrorOCode);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1ErrorOMsg_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->ErrorOMsg = *arg2;
}


SWIGEXPORT jstring JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1ErrorOMsg_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (std::string *) & ((arg1)->ErrorOMsg);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1LoggerLevel_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->LoggerLevel = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1LoggerLevel_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int) ((arg1)->LoggerLevel);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1LogFilePath_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->LogFilePath = *arg2;
}


SWIGEXPORT jstring JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1LogFilePath_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (std::string *) & ((arg1)->LogFilePath);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1MaxPorts_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->MaxPorts = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1MaxPorts_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int) ((arg1)->MaxPorts);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1MaxInitAttempts_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->MaxInitAttempts = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1MaxInitAttempts_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int) ((arg1)->MaxInitAttempts);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1ShortTime_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ShortTime = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1ShortTime_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int) ((arg1)->ShortTime);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1LongTime_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->LongTime = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1LongTime_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int) ((arg1)->LongTime);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_new_1DispenserClass(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Dispenser::DispenserClass *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Dispenser::DispenserClass *)new Dispenser::DispenserClass();
  *(Dispenser::DispenserClass **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_delete_1DispenserClass(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1SearchSpdlogLevel(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int arg2 ;
  Dispenser::SpdlogLevels_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->SearchSpdlogLevel(arg2);
  *(Dispenser::SpdlogLevels_t **)&jresult = new Dispenser::SpdlogLevels_t(result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1SetSpdlogLevel(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  (arg1)->SetSpdlogLevel();
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1SearchSuccessCode0(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::string arg2 ;
  Dispenser::StatusCodesRow_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return 0;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return 0;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  result = (arg1)->SearchSuccessCode0(arg2);
  *(Dispenser::StatusCodesRow_t **)&jresult = new Dispenser::StatusCodesRow_t(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1SearchSuccessCode1(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::string arg2 ;
  Dispenser::StatusCodesRow_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return 0;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return 0;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  result = (arg1)->SearchSuccessCode1(arg2);
  *(Dispenser::StatusCodesRow_t **)&jresult = new Dispenser::StatusCodesRow_t(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1SearchSuccessCode2(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::string arg2 ;
  Dispenser::StatusCodesRow_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return 0;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return 0;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  result = (arg1)->SearchSuccessCode2(arg2);
  *(Dispenser::StatusCodesRow_t **)&jresult = new Dispenser::StatusCodesRow_t(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1SearchErrorCode(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::string arg2 ;
  Dispenser::ErrorCodesRow_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return 0;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return 0;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  result = (arg1)->SearchErrorCode(arg2);
  *(Dispenser::ErrorCodesRow_t **)&jresult = new Dispenser::ErrorCodesRow_t(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1SearchErrorCodeExComm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int arg2 ;
  Dispenser::ErrorCodeExComm_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->SearchErrorCodeExComm(arg2);
  *(Dispenser::ErrorCodeExComm_t **)&jresult = new Dispenser::ErrorCodeExComm_t(result); 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1StIdle(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int)(arg1)->StIdle();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1StConnect(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int)(arg1)->StConnect();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1StInit(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int)(arg1)->StInit();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1StWait(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int)(arg1)->StWait();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1StMovingMotor(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int)(arg1)->StMovingMotor();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1StHandingCard(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int)(arg1)->StHandingCard();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1StError(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int)(arg1)->StError();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1InitLogger(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->InitLogger((std::string const &)*arg2);
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1ConnectSerial(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (int)(arg1)->ConnectSerial(arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1ScanPorts(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int)(arg1)->ScanPorts();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1SendingCommand(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jint jarg3) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::vector< unsigned char > arg2 ;
  int arg3 ;
  std::vector< unsigned char > *argp2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  argp2 = *(std::vector< unsigned char > **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null std::vector< unsigned char >");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (int)jarg3; 
  result = (int)(arg1)->SendingCommand(arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1ExecuteCommand(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jint jarg3) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::vector< unsigned char > arg2 ;
  int arg3 ;
  std::vector< unsigned char > *argp2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  argp2 = *(std::vector< unsigned char > **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null std::vector< unsigned char >");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (int)jarg3; 
  result = (int)(arg1)->ExecuteCommand(arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1HandleResponse(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jint jarg3, jint jarg4) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::vector< unsigned char > arg2 ;
  int arg3 ;
  int arg4 ;
  std::vector< unsigned char > *argp2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  argp2 = *(std::vector< unsigned char > **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null std::vector< unsigned char >");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (int)(arg1)->HandleResponse(arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1WriteAck(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int)(arg1)->WriteAck();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1HandleResponseSuccess(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::vector< unsigned char > arg2 ;
  std::vector< unsigned char > *argp2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  argp2 = *(std::vector< unsigned char > **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null std::vector< unsigned char >");
    return 0;
  }
  arg2 = *argp2; 
  result = (int)(arg1)->HandleResponseSuccess(arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1HandleResponseError(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  std::vector< unsigned char > arg2 ;
  std::vector< unsigned char > *argp2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  argp2 = *(std::vector< unsigned char > **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null std::vector< unsigned char >");
    return 0;
  }
  arg2 = *argp2; 
  result = (int)(arg1)->HandleResponseError(arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1InitDispenser(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int)(arg1)->InitDispenser();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1DispenseCard(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int)(arg1)->DispenseCard();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1CheckStatus(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int)(arg1)->CheckStatus();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1ReturnCardToBox(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (int)(arg1)->ReturnCardToBox();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserClass_1PrintCheck(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  (arg1)->PrintCheck();
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_SMClass_1StateMachine_1t_1CurrState_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  StateMachine::SMClass::StateMachine_t *arg1 = (StateMachine::SMClass::StateMachine_t *) 0 ;
  StateMachine::SMClass::State_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(StateMachine::SMClass::StateMachine_t **)&jarg1; 
  arg2 = (StateMachine::SMClass::State_t)jarg2; 
  if (arg1) (arg1)->CurrState = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_SMClass_1StateMachine_1t_1CurrState_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  StateMachine::SMClass::StateMachine_t *arg1 = (StateMachine::SMClass::StateMachine_t *) 0 ;
  StateMachine::SMClass::State_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(StateMachine::SMClass::StateMachine_t **)&jarg1; 
  result = (StateMachine::SMClass::State_t) ((arg1)->CurrState);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_new_1SMClass_1StateMachine_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  StateMachine::SMClass::StateMachine_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (StateMachine::SMClass::StateMachine_t *)new StateMachine::SMClass::StateMachine_t();
  *(StateMachine::SMClass::StateMachine_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_delete_1SMClass_1StateMachine_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  StateMachine::SMClass::StateMachine_t *arg1 = (StateMachine::SMClass::StateMachine_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(StateMachine::SMClass::StateMachine_t **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_new_1SMClass(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Dispenser::DispenserClass *arg1 = (Dispenser::DispenserClass *) 0 ;
  StateMachine::SMClass *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Dispenser::DispenserClass **)&jarg1; 
  result = (StateMachine::SMClass *)new StateMachine::SMClass(arg1);
  *(StateMachine::SMClass **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_SMClass_1SM_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  StateMachine::SMClass *arg1 = (StateMachine::SMClass *) 0 ;
  StateMachine::SMClass::StateMachine_t *arg2 = (StateMachine::SMClass::StateMachine_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(StateMachine::SMClass **)&jarg1; 
  arg2 = *(StateMachine::SMClass::StateMachine_t **)&jarg2; 
  if (arg1) (arg1)->SM = *arg2;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_SMClass_1SM_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  StateMachine::SMClass *arg1 = (StateMachine::SMClass *) 0 ;
  StateMachine::SMClass::StateMachine_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(StateMachine::SMClass **)&jarg1; 
  result = (StateMachine::SMClass::StateMachine_t *)& ((arg1)->SM);
  *(StateMachine::SMClass::StateMachine_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_SMClass_1LS_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  StateMachine::SMClass *arg1 = (StateMachine::SMClass *) 0 ;
  StateMachine::SMClass::StateMachine_t *arg2 = (StateMachine::SMClass::StateMachine_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(StateMachine::SMClass **)&jarg1; 
  arg2 = *(StateMachine::SMClass::StateMachine_t **)&jarg2; 
  if (arg1) (arg1)->LS = *arg2;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_SMClass_1LS_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  StateMachine::SMClass *arg1 = (StateMachine::SMClass *) 0 ;
  StateMachine::SMClass::StateMachine_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(StateMachine::SMClass **)&jarg1; 
  result = (StateMachine::SMClass::StateMachine_t *)& ((arg1)->LS);
  *(StateMachine::SMClass::StateMachine_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_SMClass_1Evento_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  StateMachine::SMClass *arg1 = (StateMachine::SMClass *) 0 ;
  StateMachine::SMClass::Event_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(StateMachine::SMClass **)&jarg1; 
  arg2 = (StateMachine::SMClass::Event_t)jarg2; 
  if (arg1) (arg1)->Evento = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_SMClass_1Evento_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  StateMachine::SMClass *arg1 = (StateMachine::SMClass *) 0 ;
  StateMachine::SMClass::Event_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(StateMachine::SMClass **)&jarg1; 
  result = (StateMachine::SMClass::Event_t) ((arg1)->Evento);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_SMClass_1Estado_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  StateMachine::SMClass *arg1 = (StateMachine::SMClass *) 0 ;
  StateMachine::SMClass::State_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(StateMachine::SMClass **)&jarg1; 
  arg2 = (StateMachine::SMClass::State_t)jarg2; 
  if (arg1) (arg1)->Estado = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_SMClass_1Estado_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  StateMachine::SMClass *arg1 = (StateMachine::SMClass *) 0 ;
  StateMachine::SMClass::State_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(StateMachine::SMClass **)&jarg1; 
  result = (StateMachine::SMClass::State_t) ((arg1)->Estado);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_SMClass_1InitStateMachine(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  StateMachine::SMClass *arg1 = (StateMachine::SMClass *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(StateMachine::SMClass **)&jarg1; 
  (arg1)->InitStateMachine();
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_SMClass_1StateMachineRun(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jint jresult = 0 ;
  StateMachine::SMClass *arg1 = (StateMachine::SMClass *) 0 ;
  StateMachine::SMClass::Event_t arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(StateMachine::SMClass **)&jarg1; 
  arg2 = (StateMachine::SMClass::Event_t)jarg2; 
  result = (int)(arg1)->StateMachineRun(arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_SMClass_1RunCheck(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  StateMachine::SMClass *arg1 = (StateMachine::SMClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(StateMachine::SMClass **)&jarg1; 
  result = (int)(arg1)->RunCheck();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_hardware_dispenser_DispenserControlJNI_SMClass_1StateMachineGetStateName(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jstring jresult = 0 ;
  StateMachine::SMClass *arg1 = (StateMachine::SMClass *) 0 ;
  StateMachine::SMClass::State_t arg2 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(StateMachine::SMClass **)&jarg1; 
  arg2 = (StateMachine::SMClass::State_t)jarg2; 
  result = (char *)(arg1)->StateMachineGetStateName(arg2);
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_delete_1SMClass(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  StateMachine::SMClass *arg1 = (StateMachine::SMClass *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(StateMachine::SMClass **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_Response_1t_1StatusCode_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DispenserControl::Response_t *arg1 = (DispenserControl::Response_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::Response_t **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->StatusCode = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_Response_1t_1StatusCode_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DispenserControl::Response_t *arg1 = (DispenserControl::Response_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::Response_t **)&jarg1; 
  result = (int) ((arg1)->StatusCode);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_Response_1t_1Message_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  DispenserControl::Response_t *arg1 = (DispenserControl::Response_t *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::Response_t **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->Message = *arg2;
}


SWIGEXPORT jstring JNICALL Java_hardware_dispenser_DispenserControlJNI_Response_1t_1Message_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  DispenserControl::Response_t *arg1 = (DispenserControl::Response_t *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::Response_t **)&jarg1; 
  result = (std::string *) & ((arg1)->Message);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_new_1Response_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DispenserControl::Response_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (DispenserControl::Response_t *)new DispenserControl::Response_t();
  *(DispenserControl::Response_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_delete_1Response_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  DispenserControl::Response_t *arg1 = (DispenserControl::Response_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(DispenserControl::Response_t **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_Flags_1t_1RFICCardInG_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  DispenserControl::Flags_t *arg1 = (DispenserControl::Flags_t *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::Flags_t **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->RFICCardInG = arg2;
}


SWIGEXPORT jboolean JNICALL Java_hardware_dispenser_DispenserControlJNI_Flags_1t_1RFICCardInG_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  DispenserControl::Flags_t *arg1 = (DispenserControl::Flags_t *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::Flags_t **)&jarg1; 
  result = (bool) ((arg1)->RFICCardInG);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_Flags_1t_1RecyclingBoxF_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  DispenserControl::Flags_t *arg1 = (DispenserControl::Flags_t *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::Flags_t **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->RecyclingBoxF = arg2;
}


SWIGEXPORT jboolean JNICALL Java_hardware_dispenser_DispenserControlJNI_Flags_1t_1RecyclingBoxF_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  DispenserControl::Flags_t *arg1 = (DispenserControl::Flags_t *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::Flags_t **)&jarg1; 
  result = (bool) ((arg1)->RecyclingBoxF);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_Flags_1t_1CardInG_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  DispenserControl::Flags_t *arg1 = (DispenserControl::Flags_t *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::Flags_t **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->CardInG = arg2;
}


SWIGEXPORT jboolean JNICALL Java_hardware_dispenser_DispenserControlJNI_Flags_1t_1CardInG_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  DispenserControl::Flags_t *arg1 = (DispenserControl::Flags_t *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::Flags_t **)&jarg1; 
  result = (bool) ((arg1)->CardInG);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_Flags_1t_1CardsInD_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  DispenserControl::Flags_t *arg1 = (DispenserControl::Flags_t *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::Flags_t **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->CardsInD = arg2;
}


SWIGEXPORT jboolean JNICALL Java_hardware_dispenser_DispenserControlJNI_Flags_1t_1CardsInD_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  DispenserControl::Flags_t *arg1 = (DispenserControl::Flags_t *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::Flags_t **)&jarg1; 
  result = (bool) ((arg1)->CardsInD);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_Flags_1t_1DispenserF_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  DispenserControl::Flags_t *arg1 = (DispenserControl::Flags_t *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::Flags_t **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->DispenserF = arg2;
}


SWIGEXPORT jboolean JNICALL Java_hardware_dispenser_DispenserControlJNI_Flags_1t_1DispenserF_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  DispenserControl::Flags_t *arg1 = (DispenserControl::Flags_t *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::Flags_t **)&jarg1; 
  result = (bool) ((arg1)->DispenserF);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_new_1Flags_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DispenserControl::Flags_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (DispenserControl::Flags_t *)new DispenserControl::Flags_t();
  *(DispenserControl::Flags_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_delete_1Flags_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  DispenserControl::Flags_t *arg1 = (DispenserControl::Flags_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(DispenserControl::Flags_t **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_TestStatus_1t_1Version_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  DispenserControl::TestStatus_t *arg1 = (DispenserControl::TestStatus_t *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::TestStatus_t **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->Version = *arg2;
}


SWIGEXPORT jstring JNICALL Java_hardware_dispenser_DispenserControlJNI_TestStatus_1t_1Version_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  DispenserControl::TestStatus_t *arg1 = (DispenserControl::TestStatus_t *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::TestStatus_t **)&jarg1; 
  result = (std::string *) & ((arg1)->Version);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_TestStatus_1t_1Device_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DispenserControl::TestStatus_t *arg1 = (DispenserControl::TestStatus_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::TestStatus_t **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->Device = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_TestStatus_1t_1Device_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DispenserControl::TestStatus_t *arg1 = (DispenserControl::TestStatus_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::TestStatus_t **)&jarg1; 
  result = (int) ((arg1)->Device);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_TestStatus_1t_1ErrorType_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DispenserControl::TestStatus_t *arg1 = (DispenserControl::TestStatus_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::TestStatus_t **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ErrorType = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_TestStatus_1t_1ErrorType_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DispenserControl::TestStatus_t *arg1 = (DispenserControl::TestStatus_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::TestStatus_t **)&jarg1; 
  result = (int) ((arg1)->ErrorType);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_TestStatus_1t_1ErrorCode_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DispenserControl::TestStatus_t *arg1 = (DispenserControl::TestStatus_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::TestStatus_t **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ErrorCode = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_TestStatus_1t_1ErrorCode_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DispenserControl::TestStatus_t *arg1 = (DispenserControl::TestStatus_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::TestStatus_t **)&jarg1; 
  result = (int) ((arg1)->ErrorCode);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_TestStatus_1t_1Message_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  DispenserControl::TestStatus_t *arg1 = (DispenserControl::TestStatus_t *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::TestStatus_t **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->Message = *arg2;
}


SWIGEXPORT jstring JNICALL Java_hardware_dispenser_DispenserControlJNI_TestStatus_1t_1Message_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  DispenserControl::TestStatus_t *arg1 = (DispenserControl::TestStatus_t *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::TestStatus_t **)&jarg1; 
  result = (std::string *) & ((arg1)->Message);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_TestStatus_1t_1AditionalInfo_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  DispenserControl::TestStatus_t *arg1 = (DispenserControl::TestStatus_t *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::TestStatus_t **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->AditionalInfo = *arg2;
}


SWIGEXPORT jstring JNICALL Java_hardware_dispenser_DispenserControlJNI_TestStatus_1t_1AditionalInfo_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  DispenserControl::TestStatus_t *arg1 = (DispenserControl::TestStatus_t *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::TestStatus_t **)&jarg1; 
  result = (std::string *) & ((arg1)->AditionalInfo);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_TestStatus_1t_1Priority_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DispenserControl::TestStatus_t *arg1 = (DispenserControl::TestStatus_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::TestStatus_t **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->Priority = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_TestStatus_1t_1Priority_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DispenserControl::TestStatus_t *arg1 = (DispenserControl::TestStatus_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::TestStatus_t **)&jarg1; 
  result = (int) ((arg1)->Priority);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_new_1TestStatus_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DispenserControl::TestStatus_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (DispenserControl::TestStatus_t *)new DispenserControl::TestStatus_t();
  *(DispenserControl::TestStatus_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_delete_1TestStatus_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  DispenserControl::TestStatus_t *arg1 = (DispenserControl::TestStatus_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(DispenserControl::TestStatus_t **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_GlobalVariables_1DispenserObject_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  DispenserControl::GlobalVariables *arg1 = (DispenserControl::GlobalVariables *) 0 ;
  Dispenser::DispenserClass *arg2 = (Dispenser::DispenserClass *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(DispenserControl::GlobalVariables **)&jarg1; 
  arg2 = *(Dispenser::DispenserClass **)&jarg2; 
  if (arg1) (arg1)->DispenserObject = *arg2;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_GlobalVariables_1DispenserObject_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DispenserControl::GlobalVariables *arg1 = (DispenserControl::GlobalVariables *) 0 ;
  Dispenser::DispenserClass *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::GlobalVariables **)&jarg1; 
  result = (Dispenser::DispenserClass *)& ((arg1)->DispenserObject);
  *(Dispenser::DispenserClass **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_GlobalVariables_1DispenserPointer_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  DispenserControl::GlobalVariables *arg1 = (DispenserControl::GlobalVariables *) 0 ;
  Dispenser::DispenserClass *arg2 = (Dispenser::DispenserClass *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(DispenserControl::GlobalVariables **)&jarg1; 
  arg2 = *(Dispenser::DispenserClass **)&jarg2; 
  if (arg1) (arg1)->DispenserPointer = arg2;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_GlobalVariables_1DispenserPointer_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DispenserControl::GlobalVariables *arg1 = (DispenserControl::GlobalVariables *) 0 ;
  Dispenser::DispenserClass *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::GlobalVariables **)&jarg1; 
  result = (Dispenser::DispenserClass *) ((arg1)->DispenserPointer);
  *(Dispenser::DispenserClass **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_GlobalVariables_1SMObject_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  DispenserControl::GlobalVariables *arg1 = (DispenserControl::GlobalVariables *) 0 ;
  StateMachine::SMClass *arg2 = (StateMachine::SMClass *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(DispenserControl::GlobalVariables **)&jarg1; 
  arg2 = *(StateMachine::SMClass **)&jarg2; 
  if (arg1) (arg1)->SMObject = *arg2;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_GlobalVariables_1SMObject_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DispenserControl::GlobalVariables *arg1 = (DispenserControl::GlobalVariables *) 0 ;
  StateMachine::SMClass *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::GlobalVariables **)&jarg1; 
  result = (StateMachine::SMClass *)& ((arg1)->SMObject);
  *(StateMachine::SMClass **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_new_1GlobalVariables(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DispenserControl::GlobalVariables *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (DispenserControl::GlobalVariables *)new DispenserControl::GlobalVariables();
  *(DispenserControl::GlobalVariables **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_delete_1GlobalVariables(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  DispenserControl::GlobalVariables *arg1 = (DispenserControl::GlobalVariables *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(DispenserControl::GlobalVariables **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1PortO_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->PortO = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1PortO_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (int) ((arg1)->PortO);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1Path_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->Path = *arg2;
}


SWIGEXPORT jstring JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1Path_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (std::string *) & ((arg1)->Path);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1LogLvl_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->LogLvl = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1LogLvl_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (int) ((arg1)->LogLvl);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1MaximumPorts_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->MaximumPorts = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1MaximumPorts_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (int) ((arg1)->MaximumPorts);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1MaxInitAttempts_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->MaxInitAttempts = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1MaxInitAttempts_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (int) ((arg1)->MaxInitAttempts);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1ShortTime_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->ShortTime = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1ShortTime_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (int) ((arg1)->ShortTime);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1LongTime_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->LongTime = arg2;
}


SWIGEXPORT jint JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1LongTime_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (int) ((arg1)->LongTime);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1Globals_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  DispenserControl::GlobalVariables *arg2 = (DispenserControl::GlobalVariables *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  arg2 = *(DispenserControl::GlobalVariables **)&jarg2; 
  if (arg1) (arg1)->Globals = *arg2;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1Globals_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  DispenserControl::GlobalVariables *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (DispenserControl::GlobalVariables *)& ((arg1)->Globals);
  *(DispenserControl::GlobalVariables **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_new_1DispenserControlClass(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DispenserControl::DispenserControlClass *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (DispenserControl::DispenserControlClass *)new DispenserControl::DispenserControlClass();
  *(DispenserControl::DispenserControlClass **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_delete_1DispenserControlClass(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1InitLog(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  (arg1)->InitLog();
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1Connect(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  DispenserControl::Response_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (arg1)->Connect();
  *(DispenserControl::Response_t **)&jresult = new DispenserControl::Response_t(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1CheckDevice(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  DispenserControl::Response_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (arg1)->CheckDevice();
  *(DispenserControl::Response_t **)&jresult = new DispenserControl::Response_t(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1CheckCodes(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  DispenserControl::Response_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (arg1)->CheckCodes();
  *(DispenserControl::Response_t **)&jresult = new DispenserControl::Response_t(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1DispenseCard(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  DispenserControl::Response_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (arg1)->DispenseCard();
  *(DispenserControl::Response_t **)&jresult = new DispenserControl::Response_t(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1RecycleCard(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  DispenserControl::Response_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (arg1)->RecycleCard();
  *(DispenserControl::Response_t **)&jresult = new DispenserControl::Response_t(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1EndProcess(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  DispenserControl::Response_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (arg1)->EndProcess();
  *(DispenserControl::Response_t **)&jresult = new DispenserControl::Response_t(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1GetDispenserFlags(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  DispenserControl::Flags_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (arg1)->GetDispenserFlags();
  *(DispenserControl::Flags_t **)&jresult = new DispenserControl::Flags_t(result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_hardware_dispenser_DispenserControlJNI_DispenserControlClass_1TestStatus(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DispenserControl::DispenserControlClass *arg1 = (DispenserControl::DispenserControlClass *) 0 ;
  DispenserControl::TestStatus_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DispenserControl::DispenserControlClass **)&jarg1; 
  result = (arg1)->TestStatus();
  *(DispenserControl::TestStatus_t **)&jresult = new DispenserControl::TestStatus_t(result); 
  return jresult;
}


#ifdef __cplusplus
}
#endif

