/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hardware.dispenser;

public class DispenserControlClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DispenserControlClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DispenserControlClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DispenserControlClass obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DispenserControlJNI.delete_DispenserControlClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPortO(int value) {
    DispenserControlJNI.DispenserControlClass_PortO_set(swigCPtr, this, value);
  }

  public int getPortO() {
    return DispenserControlJNI.DispenserControlClass_PortO_get(swigCPtr, this);
  }

  public void setPath(String value) {
    DispenserControlJNI.DispenserControlClass_Path_set(swigCPtr, this, value);
  }

  public String getPath() {
    return DispenserControlJNI.DispenserControlClass_Path_get(swigCPtr, this);
  }

  public void setLogLvl(int value) {
    DispenserControlJNI.DispenserControlClass_LogLvl_set(swigCPtr, this, value);
  }

  public int getLogLvl() {
    return DispenserControlJNI.DispenserControlClass_LogLvl_get(swigCPtr, this);
  }

  public void setMaximumPorts(int value) {
    DispenserControlJNI.DispenserControlClass_MaximumPorts_set(swigCPtr, this, value);
  }

  public int getMaximumPorts() {
    return DispenserControlJNI.DispenserControlClass_MaximumPorts_get(swigCPtr, this);
  }

  public void setMaxInitAttempts(int value) {
    DispenserControlJNI.DispenserControlClass_MaxInitAttempts_set(swigCPtr, this, value);
  }

  public int getMaxInitAttempts() {
    return DispenserControlJNI.DispenserControlClass_MaxInitAttempts_get(swigCPtr, this);
  }

  public void setShortTime(int value) {
    DispenserControlJNI.DispenserControlClass_ShortTime_set(swigCPtr, this, value);
  }

  public int getShortTime() {
    return DispenserControlJNI.DispenserControlClass_ShortTime_get(swigCPtr, this);
  }

  public void setLongTime(int value) {
    DispenserControlJNI.DispenserControlClass_LongTime_set(swigCPtr, this, value);
  }

  public int getLongTime() {
    return DispenserControlJNI.DispenserControlClass_LongTime_get(swigCPtr, this);
  }

  public void setGlobals(GlobalVariables value) {
    DispenserControlJNI.DispenserControlClass_Globals_set(swigCPtr, this, GlobalVariables.getCPtr(value), value);
  }

  public GlobalVariables getGlobals() {
    long cPtr = DispenserControlJNI.DispenserControlClass_Globals_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GlobalVariables(cPtr, false);
  }

  public DispenserControlClass() {
    this(DispenserControlJNI.new_DispenserControlClass(), true);
  }

  public void InitLog() {
    DispenserControlJNI.DispenserControlClass_InitLog(swigCPtr, this);
  }

  public Response_t Connect() {
    return new Response_t(DispenserControlJNI.DispenserControlClass_Connect(swigCPtr, this), true);
  }

  public Response_t CheckDevice() {
    return new Response_t(DispenserControlJNI.DispenserControlClass_CheckDevice(swigCPtr, this), true);
  }

  public Response_t CheckCodes() {
    return new Response_t(DispenserControlJNI.DispenserControlClass_CheckCodes(swigCPtr, this), true);
  }

  public Response_t DispenseCard() {
    return new Response_t(DispenserControlJNI.DispenserControlClass_DispenseCard(swigCPtr, this), true);
  }

  public Response_t RecycleCard() {
    return new Response_t(DispenserControlJNI.DispenserControlClass_RecycleCard(swigCPtr, this), true);
  }

  public Response_t EndProcess() {
    return new Response_t(DispenserControlJNI.DispenserControlClass_EndProcess(swigCPtr, this), true);
  }

  public Flags_t GetDispenserFlags() {
    return new Flags_t(DispenserControlJNI.DispenserControlClass_GetDispenserFlags(swigCPtr, this), true);
  }

  public TestStatus_t TestStatus() {
    return new TestStatus_t(DispenserControlJNI.DispenserControlClass_TestStatus(swigCPtr, this), true);
  }

}
