/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hardware.dispenser;

public class Flags_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Flags_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Flags_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Flags_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DispenserControlJNI.delete_Flags_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRFICCardInG(boolean value) {
    DispenserControlJNI.Flags_t_RFICCardInG_set(swigCPtr, this, value);
  }

  public boolean getRFICCardInG() {
    return DispenserControlJNI.Flags_t_RFICCardInG_get(swigCPtr, this);
  }

  public void setRecyclingBoxF(boolean value) {
    DispenserControlJNI.Flags_t_RecyclingBoxF_set(swigCPtr, this, value);
  }

  public boolean getRecyclingBoxF() {
    return DispenserControlJNI.Flags_t_RecyclingBoxF_get(swigCPtr, this);
  }

  public void setCardInG(boolean value) {
    DispenserControlJNI.Flags_t_CardInG_set(swigCPtr, this, value);
  }

  public boolean getCardInG() {
    return DispenserControlJNI.Flags_t_CardInG_get(swigCPtr, this);
  }

  public void setCardsInD(boolean value) {
    DispenserControlJNI.Flags_t_CardsInD_set(swigCPtr, this, value);
  }

  public boolean getCardsInD() {
    return DispenserControlJNI.Flags_t_CardsInD_get(swigCPtr, this);
  }

  public void setDispenserF(boolean value) {
    DispenserControlJNI.Flags_t_DispenserF_set(swigCPtr, this, value);
  }

  public boolean getDispenserF() {
    return DispenserControlJNI.Flags_t_DispenserF_get(swigCPtr, this);
  }

  public Flags_t() {
    this(DispenserControlJNI.new_Flags_t(), true);
  }

}
