/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hardware.dispenser;

public class StatusCodesRow_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StatusCodesRow_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StatusCodesRow_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(StatusCodesRow_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DispenserControlJNI.delete_StatusCodesRow_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStatus(String value) {
    DispenserControlJNI.StatusCodesRow_t_Status_set(swigCPtr, this, value);
  }

  public String getStatus() {
    return DispenserControlJNI.StatusCodesRow_t_Status_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    DispenserControlJNI.StatusCodesRow_t_Message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return DispenserControlJNI.StatusCodesRow_t_Message_get(swigCPtr, this);
  }

  public void setPriority(int value) {
    DispenserControlJNI.StatusCodesRow_t_Priority_set(swigCPtr, this, value);
  }

  public int getPriority() {
    return DispenserControlJNI.StatusCodesRow_t_Priority_get(swigCPtr, this);
  }

  public StatusCodesRow_t() {
    this(DispenserControlJNI.new_StatusCodesRow_t(), true);
  }

}
